config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user, ->(u) { u.admin? } do
    resources :announcements

    namespace :admin do
      resources :users
      resources :announcements

      root to: 'announcements#index'
    end
  end

  authenticated :user do
    resources :announcements, only: %i[index show]
  end

  devise_for :users
  get 'welcome/index'
  resource :api_token
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/announcement.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: announcements
#
#  id         :bigint           not null, primary key
#  title      :string
#  body       :text
#  category   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Announcement < ApplicationRecord
  paginates_per 5
end

app/controllers/admin/announcements_controller.rb
module Admin
  class AnnouncementsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/announcements_controller.rb
# frozen_string_literal: true

class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: %i[show edit update destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    # @announcements = Announcement.all
    @announcements = Announcement.order(:title).page params[:page]
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show; end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit; end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_announcement
    @announcement = Announcement.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def announcement_params
    params.require(:announcement).permit(:title, :body, :category)
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>
      <ul>
        <% announcement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary my-3' %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>
<%= render 'form', announcement: @announcement %>
<%= link_to 'Show', @announcement, class: 'btn-sm btn-primary' %> |
<%= link_to 'Back', announcements_path, class: 'btn-sm btn-primary' %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Announcements</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.title %></td>
        <td><%= announcement.body %></td>
        <td><%= announcement.category %></td>
        <td><%= link_to 'Show', announcement, class: "btn-sm btn-primary" %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_announcement_path(announcement), class: "btn-sm btn-primary" %></td>
          <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-primary" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @announcements %>
<br>
<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>
<div class="shadow-lg p-5">
  <p>
    <strong>Title:</strong>
    <%= @announcement.title %>
  </p>
  <p>
    <strong>Body:</strong>
    <%= @announcement.body %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= @announcement.category %>
  </p>
  <%= link_to 'Edit', edit_announcement_path(@announcement), class: 'btn-sm btn-primary' %> |
  <%= link_to 'Back', announcements_path, class: 'btn-sm btn-primary' %>
</div>